node01:
    image: cassandra:3.11.1
    container_name: cass_node1
    ports:
        - "7000:7000"
        - "7001:7001"
        - "9042:9042"
        - "9160:9160"
        - "7199:7199"
    volumes:
        - ./data1:/var/lib/cassandra
   
node02:
    image: cassandra:3.11.1
    container_name: cass_node2
    ports:
        - "17000:7000"
        - "17001:7001"
        - "19042:9042"
        - "19160:9160"
        - "17199:7199"
    volumes:
        - ./data2:/var/lib/cassandra
    environment:
        - CASSANDRA_SEEDS=node01
    links:
        - node01:node01

node03:
    image: cassandra:3.11.1
    container_name: cass_node3
    ports:
        - "27000:7000"
        - "27001:7001"
        - "29042:9042"
        - "29160:9160"
        - "27199:7199"
    volumes:
        - ./data3:/var/lib/cassandra
    environment:
        - CASSANDRA_SEEDS=node01
    links:
        - node01:node01
        
spark-master:
    image: uq/spark
    container_name: spark-master
    environment:
        - SPARK_TYPE=master
    ports:
        - 8080:8080
        
spark-worker-1:
    image: uq/spark
    container_name: spark-worker-1
    environment:
      - SPARK_TYPE=slave
      - SPARK_MASTERS=spark-master
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    links:
      - spark-master
  
spark-worker-2:
    image: uq/spark
    container_name: spark-worker-2
    environment:
      - SPARK_TYPE=slave
      - SPARK_MASTERS=spark-master
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    links:
      - spark-master

zeppelin:
  build: .
  container_name: zeppelin
  environment:
    ZEPPELIN_PORT: 8090
    ZEPPELIN_JAVA_OPTS: >-
      -Dspark.driver.memory=1g
      -Dspark.executor.memory=2g
    SPARK_SUBMIT_OPTIONS: >-
      --conf spark.driver.host=localhost
      --conf spark.driver.port=8081
      --conf spark.es.port=9200
      --packages datastax:spark-cassandra-connector:2.0.0-M2-s_2.11
      --conf spark.cassandra.connection.host=cassandra
      --conf cassandra.hosts=cassandra
    MASTER: local[*]
  links:
    - node01:cassandra
    - spark-master
  ports:
    - 8090:8090
    - 8091:8091
  volumes:
    - ./znotebooks:/usr/zeppelin/notebook
