node01:
    image: cassandra:3.11.1
    container_name: cass_node1
    ports:
        - "7000:7000"
        - "7001:7001"
        - "9042:9042"
        - "9160:9160"
        - "7199:7199"
    volumes:
        - /home/minhnln/vboxshare/Zepp-Cass-Spark/shared-data/Cass1:/shared-data
   
node02:
    image: cassandra:3.11.1
    container_name: cass_node2
    ports:
        - "17000:7000"
        - "17001:7001"
        - "19042:9042"
        - "19160:9160"
        - "17199:7199"
    volumes:
        - /home/minhnln/vboxshare/Zepp-Cass-Spark/shared-data/Cass2:/shared-data
    environment:
        - CASSANDRA_SEEDS=node01
    links:
        - node01:node01
        
spark-master:
    image: uq/spark
    container_name: spark-master
    environment:
        - SPARK_TYPE=master
    ports:
        - 8080:8080
        - 4040:4040
        
spark-worker-1:
    image: uq/spark
    container_name: spark-worker-1
    environment:
        - SPARK_TYPE=slave
        - SPARK_MASTERS=spark-master
        - SPARK_WORKER_CORES=48
        - SPARK_WORKER_MEMORY=2g
    links:
        - spark-master
        - zeppelin
    ports:
        - 8081:8081

zeppelin:
  build: .
  container_name: zeppelin
  environment:
    ZEPPELIN_PORT: 8090
    ZEPPELIN_JAVA_OPTS: >-
      -Dspark.driver.memory=1g
      -Dspark.executor.memory=2g
    SPARK_SUBMIT_OPTIONS: >-
      --packages datastax:spark-cassandra-connector:2.0.0-M2-s_2.11
      --conf spark.cassandra.connection.host=cassandra
      --conf cassandra.hosts=cassandra
    MASTER: local[*]
  links:
    - node01:cassandra
    - spark-master
  ports:
    - 8090:8090
    - 8091:8091
    
  volumes:
    - ./znotebooks:/usr/zeppelin/notebook
    
phpwebserver:
    image: myphpcass
    container_name: phpwebserver
    ports:
        - 8070:80
    links:
        - node01:cassandra
    volumes:
        - /home/minhnln/vboxshare/Zepp-Cass-Spark/shared-data/public_html:/var/www/html
