spark-master:
    image: uq/spark
    container_name: spark-master
    environment:
        - SPARK_TYPE=master
        
spark-worker-1:
    image: uq/spark
    container_name: spark-worker-1
    environment:
      - SPARK_TYPE=slave
      - SPARK_MASTERS=spark-master
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    links:
      - spark-master
  
spark-worker-2:
    image: uq/spark
    container_name: spark-worker-2
    environment:
      - SPARK_TYPE=slave
      - SPARK_MASTERS=spark-master
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    links:
      - spark-master