version: "2.1"

services:
    zoo1:
        image: zookeeper
        restart: always
        container_name: zoo1
        hostname: zoo1
        ports:
          - 2181:2181
        environment:
          ZOO_MY_ID: 1
          ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888

    zoo2:
        image: zookeeper
        restart: always
        container_name: zoo2
        hostname: zoo2
        ports:
          - 2182:2181
        environment:
          ZOO_MY_ID: 2
          ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888

    node01:
        image: cassandra:3.11.1
        container_name: cass_node1
        ports:
            - "7000:7000"
            - "7001:7001"
            - "9042:9042"
            - "9160:9160"
            - "7199:7199"
        volumes:
            - /CloudAssignment/Cass1:/shared-data
        environment:
            - CASSANDRA_SEEDS=node01,node02,node03
            - CASSANDRA_START_RPC=true
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
            interval: 60s
            timeout: 10s
            retries: 5        
       
    node02:
        image: cassandra:3.11.1
        container_name: cass_node2
        ports:
            - "17000:7000"
            - "17001:7001"
            - "19042:9042"
            - "19160:9160"
            - "17199:7199"
        volumes:
            - /CloudAssignment/Cass2:/shared-data
        environment:
            - CASSANDRA_SEEDS=node01,node02,node03
            - CASSANDRA_START_RPC=true
        restart: always
        links:
            - node01:node01
        depends_on:
            node01: 
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
            interval: 30s
            timeout: 10s
            retries: 5
            
    node03:
        image: cassandra:3.11.1
        container_name: cass_node3
        ports:
            - "27000:7000"
            - "27001:7001"
            - "29042:9042"
            - "29160:9160"
            - "27199:7199"
        volumes:
            - /CloudAssignment/Cass3:/shared-data
        environment:
            - CASSANDRA_SEEDS=node01,node02,node03
            - CASSANDRA_START_RPC=true
        restart: always
        links:
            - node01:node01
        depends_on:
            node01: 
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
            interval: 30s
            timeout: 10s
            retries: 5
            
    spark-master:
        build: ./spark
        container_name: spark-master
        restart: always
        environment:
            SPARK_TYPE: master
            SPARK_MASTER_OPTS: >-
                -Dspark.deploy.recoveryMode=ZOOKEEPER
                -Dspark.deploy.zookeeper.url=zoo1:2181,zoo2:2182
        ports:
            - 8080:8080
            - 4040:4040
        links:
            - zoo1
            - zoo2
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 50s
            timeout: 10s
            retries: 3
            
    spark-master-backup:

        build: ./spark
        container_name: spark-master-backup
        restart: always
        environment:
            SPARK_TYPE: master
            SPARK_MASTER_OPTS: >-
                -Dspark.deploy.recoveryMode=ZOOKEEPER
                -Dspark.deploy.zookeeper.url=zoo1:2181,zoo2:2182
        ports:
            - 8081:8080
            - 4041:4040
        links:
            - zoo1
            - zoo2
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081"]
            interval: 50s
            timeout: 10s
            retries: 3
            
    spark-worker-1:
        build: ./spark
        container_name: spark-worker-1
        environment:
            - SPARK_TYPE=slave
            - SPARK_MASTERS=spark://spark-master-backup:7077,spark-master:7077
            - SPARK_WORKER_CORES=32
            - SPARK_WORKER_MEMORY=2g
        links:
            - spark-master
            - spark-master-backup
        ports:
            - 8082:8082
        depends_on:
            spark-master: 
                condition: service_healthy
     
    spark-worker-2:
        build: ./spark
        container_name: spark-worker-2
        environment:
            - SPARK_TYPE=slave
            - SPARK_MASTERS=spark-master
            - SPARK_WORKER_CORES=32
            - SPARK_WORKER_MEMORY=2g
        links:
            - spark-master
            - spark-master-backup
        ports:
            - 8083:8083
        depends_on:
            spark-master: 
                condition: service_healthy
                
    zeppelin:
      build: ./zeppelin
      container_name: zeppelin
      environment:
        ZEPPELIN_PORT: 8090
        ZEPPELIN_JAVA_OPTS: >-
          -Dspark.driver.memory=1g
          -Dspark.executor.memory=2g
        SPARK_SUBMIT_OPTIONS: >-
          --packages datastax:spark-cassandra-connector:2.0.0-M2-s_2.11
          --conf spark.cassandra.connection.host=cassandra
          --conf cassandra.hosts=cassandra
        MASTER: local[*]
      links:
        - node01:cassandra
        - spark-master
      ports:
        - 8090:8090
        - 8091:8091
      volumes:
        - ./znotebooks:/usr/zeppelin/notebook
      healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8090"]
            interval: 50s
            timeout: 3s
            retries: 3
      depends_on:
            spark-master: 
                condition: service_healthy
            node01: 
                condition: service_healthy
                
    phpwebserver:
        build: ./phpcass
        container_name: phpwebserver
        ports:
            - 8070:80
        links:
            - node01:cassandra
        volumes:
            - /CloudAssignment/public_html:/var/www/html
        depends_on:
            node01: 
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 5s
            timeout: 3s
            retries: 3
